version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: npm
    directory: "/example-astro"
    schedule:
      interval: weekly
      day: monday
    groups:
      example-astro:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: "/example-jekyll"
    schedule:
      interval: weekly
      day: monday
    groups:
      example-jekyll:
        patterns:
          - "*"
